#!/usr/bin/bash

ME="https://www.github.com/brnt-toast/"
repos=("portfolio" "dotfiles" "scripts" "CookBook" "virtual-lab")

for i in "${repos[@]}"; # [@] expands out the repos array
do
        git clone "$ME$i"
done

git clone https://www.gitlab.com/brnt-toast/notes.git
