#!/usr/bin/env bash

sudo apt update -y && sudo apt upgrade -y

sudo apt install vim -y \
		htop -y \
		curl -y \
		ranger -y \
		tmux -y \
		python3 -y \
		python3-pip -y \
		python3 -m pip install ipython
		
# NOTE: Make this a python script with actual testing 
# install DOCKER & NVM



