#!/usr/bin/env python3

import random 
import os

data = {
    "fish" : "}~<(((*>" , 
    "questioning" : "＼(°ロ＼)", 
    "come on" : "щ(ﾟДﾟщ)", 
    "run" : "ε=ε=ε=┌(;*´Д`)ﾉ",
    "face_palm" : "(－‸ლ)",
    "disapproval" : "ಠ_ಠ",
    "homer" : "~(_8^(I)",
    "mad" : ">:[" ,
    "fingers" : "(凸ಠ益ಠ)凸"
}

def random_index_key():
    return random.randrange(len(data.items()))

data_array  = [i for i in enumerate(data)]
name = data_array [random_index_key()][1]
emoticon = r'{}'.format(data[name])

cmd = r"git add .; git commit -m '{}'".format(emoticon)

os.system(cmd)